<a href="https://colab.research.google.com/github/ExplorerGumel/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [63]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [64]:
# Import torch
import torch

# Create random tensor

tensor_A = torch.rand(7,7)
tensor_A

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [65]:
# Create another random tensor
tensor_B = torch.rand(1,7)
# Perform matrix multiplication
multiply = torch.matmul(tensor_A, tensor_B.T)
multiply

tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
import random
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
seed_A = torch.rand(7,7)

torch.manual_seed(seed=RANDOM_SEED)
seed_B = torch.rand(1,7)
# Matrix multiply tensors
seed_multiply = torch.matmul(seed_A, seed_B.T)
seed_multiply

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [66]:
# Set random seed on the GPU
torch.cuda.manual_seed(42)
device = torch.device("cuda")

cuda_A = torch.rand(7, 7, device=device)
cuda_A

tensor([[0.6130, 0.0101, 0.3984, 0.0403, 0.1563, 0.4825, 0.7362],
        [0.4060, 0.5189, 0.2867, 0.2416, 0.9228, 0.8299, 0.0342],
        [0.3879, 0.0824, 0.7742, 0.2792, 0.5138, 0.2068, 0.0074],
        [0.8750, 0.9682, 0.1201, 0.1972, 0.4503, 0.0511, 0.4892],
        [0.9331, 0.3807, 0.0509, 0.2663, 0.6495, 0.2675, 0.1733],
        [0.8565, 0.2761, 0.2093, 0.0711, 0.7701, 0.6100, 0.3444],
        [0.9852, 0.4692, 0.9203, 0.7127, 0.1052, 0.8138, 0.1092]],
       device='cuda:0')


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [67]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
print(f"The status of cuda availability is: {torch.cuda.is_available()}")
# Create two random tensors on GPU
device = torch.device("cuda")

tensor_1 = torch.rand(2,3, device=device)
print(tensor_1)

torch.manual_seed(1234)
tensor_2 = torch.rand(2,3, device=device)
print(tensor_2)

The status of cuda availability is: True
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [68]:
# Perform matmul on tensor_A and tensor_B
matmul = torch.matmul(tensor_1, tensor_2.T)
print(matmul)

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [71]:
# Find max
max = torch.max(matmul)
print(max)
# Find min
min = torch.min(matmul)
print(min)

tensor(1.4578, device='cuda:0')
tensor(0.8358, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [72]:
# Find arg max
arg_max = torch.argmax(matmul)
print(arg_max)
# Find arg min
arg_min = torch.argmin(matmul)
print(arg_min)

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [73]:
# Set seed
seed = 7
torch.manual_seed(seed)
# Create random tensor
rand_1 = torch.rand(1,1,1,10, dtype=torch.float32)
# Remove single dimensions
rand_2 = torch.squeeze(rand_1)
# Print out tensors and their shapes
print(f"The first tensor is\n {rand_1}\n It's shape is: {rand_1.shape}")
print(f"The second tensor is\n {rand_2}\n It's shape is: {rand_2.shape}")

The first tensor is
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
 It's shape is: torch.Size([1, 1, 1, 10])
The second tensor is
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
 It's shape is: torch.Size([10])
